import { Restaurant, Review } from './types';

export const RESTAURANTS: Restaurant[] = [
  {
    id: 1,
    name: "Riwaayat",
    address: "Jaisalmer Fort Road, Jaisalmer, Rajasthan",
    cuisine: "Indian",
    diningType: "Dine-in",
    rating: 4.8,
    reviewCount: 42,
    image: "/images/riwaayat.jpg",
  },
  {
    id: 2,
    name: "Casa Bellini",
    address: "MG Road, Jaipur, Rajasthan",
    cuisine: "Italian",
    diningType: "Dine-in",
    rating: 4.6,
    reviewCount: 28,
    image: "/images/casa-bellini.jpg",
  },
  {
    id: 3,
    name: "Naturals Ice Cream",
    address: "C.G. Road, Ahmedabad, Gujarat",
    cuisine: "Ice Cream",
    diningType: "Dessert",
    rating: 4.7,
    reviewCount: 36,
    image: "/images/naturals.jpg",
  },
];

export const INITIAL_REVIEWS: Record<number, Review[]> = {
  1: [
    {
      id: "r1-latest",
      restaurantId: 1,
      reviewerName: "Rahul Mehta",
      date: "2 days ago",
      rating: 5,
      reviewText: "The food presentation was incredible and the flavours felt genuinely Rajasthani. The royal thali was the highlight of the evening.",
      isLatest: true,
    },
    {
      id: "r1-2",
      restaurantId: 1,
      reviewerName: "Ananya Sharma",
      date: "1 week ago",
      rating: 5,
      reviewText: "Dining here felt like being a guest in a royal palace. The ker sangri, dal baati churma, and assorted breads served in traditional brassware were unforgettable.",
    },
    {
      id: "r1-3",
      restaurantId: 1,
      reviewerName: "Vikramaditya Rathore",
      date: "2 weeks ago",
      rating: 5,
      reviewText: "Incredible Rajasthani flavours with heritage atmosphere inside Jaisalmer. The curries and ghevar were rich and authentic.",
    },
    {
      id: "r1-4",
      restaurantId: 1,
      reviewerName: "Sunita Patel",
      date: "3 weeks ago",
      rating: 4,
      reviewText: "Spectacular royal thali experience. Each bowl had a distinct, authentic spice profile. Truly memorable dining.",
    },
  ],
  2: [
    {
      id: "r2-latest",
      restaurantId: 2,
      reviewerName: "Aarav Kapoor",
      date: "3 days ago",
      rating: 5,
      reviewText: "The hand-rolled tagliatelle with truffle emulsion was pure poetry. Outstanding Italian flavours with such fresh ingredients.",
      isLatest: true,
    },
    {
      id: "r2-2",
      restaurantId: 2,
      reviewerName: "Priya Nair",
      date: "1 week ago",
      rating: 4,
      reviewText: "Authentic al dente pasta and delicious wood-fired bread. The ambience on MG Road is cozy yet refined.",
    },
    {
      id: "r2-3",
      restaurantId: 2,
      reviewerName: "Rohan Deshmukh",
      date: "2 weeks ago",
      rating: 4,
      reviewText: "Loved the risotto and fresh burrata salad. A sophisticated dining atmosphere that Jaipur truly needed.",
    },
    {
      id: "r2-4",
      restaurantId: 2,
      reviewerName: "Simran Kaur",
      date: "1 month ago",
      rating: 5,
      reviewText: "One of the finest Italian dining experiences in town. The tiramisu was delicate and authentic.",
    },
  ],
  3: [
    {
      id: "r3-latest",
      restaurantId: 3,
      reviewerName: "Meera Joshi",
      date: "Yesterday",
      rating: 5,
      reviewText: "The seasonal tender coconut and fresh alphonso mango scoops were sensational. Unmatched creamy texture with natural fruit chunks!",
      isLatest: true,
    },
    {
      id: "r3-2",
      restaurantId: 3,
      reviewerName: "Kunal Shah",
      date: "5 days ago",
      rating: 5,
      reviewText: "Their roasted almond and pistachio ice creams are rich and creamy without being overly sweet. Best dessert spot on C.G. Road.",
    },
    {
      id: "r3-3",
      restaurantId: 3,
      reviewerName: "Tanvi Bhatt",
      date: "2 weeks ago",
      rating: 4,
      reviewText: "The pure fruit flavours shine through in every bite. The custard apple (sitaphal) flavor is a masterpiece.",
    },
    {
      id: "r3-4",
      restaurantId: 3,
      reviewerName: "Harshil Parikh",
      date: "3 weeks ago",
      rating: 5,
      reviewText: "Rich texture and real ingredients. The malai and mango combination is always our family go-to.",
    },
  ],
};
